### GET request for all products in category 1
GET http://localhost:8080/api/products?catId=1

### GET request for product 35
GET http://localhost:8080/api/products/35


### POST request to add new product
POST http://localhost:8080/api/products
Content-Type: application/json

{
    "categoryId": 1,
    "productName": "Ginger Beer",
    "quantityPerUnit": "18oz - 2 bottles",
    "unitPrice": 24.0,
    "unitsInStock": 20,
    "unitsOnOrder": 20,
    "reorderLevel": 10
}

### PUT request to edit a product
PUT http://localhost:8080/api/products/35
Content-Type: application/json

{
    "categoryId": 1,
    "productName": "TEST",
    "quantityPerUnit": "12oz - 10 Bottles",
    "unitPrice": 36.0,
    "unitsInStock": 40,
    "unitsOnOrder": 0,
    "reorderLevel": 15
}

### DELETE request to delete product
DELETE http://localhost:8080/api/products/35


### GET request to test Global Exception
GET http://localhost:8080/api/prod


### GET request for categories dependency injection
GET http://localhost:8080/api/categories